// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTRIVH0k0LaC7edBf1SAahAwhDFv-db8',
    appId: '1:894560350962:web:eca9af2e6e761dd28b166b',
    messagingSenderId: '894560350962',
    projectId: 'ipplanner-fdba7',
    authDomain: 'ipplanner-fdba7.firebaseapp.com',
    storageBucket: 'ipplanner-fdba7.appspot.com',
    measurementId: 'G-FLL5N8JY6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLOfhf_nfb8oaImj3ixS6vbwAi9Q-sK30',
    appId: '1:894560350962:android:c5a471b5f22244168b166b',
    messagingSenderId: '894560350962',
    projectId: 'ipplanner-fdba7',
    storageBucket: 'ipplanner-fdba7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGsK4rGgupqZCu1pwvMIUQglA_-yxnL8k',
    appId: '1:894560350962:ios:c65d353dd0c4cbc18b166b',
    messagingSenderId: '894560350962',
    projectId: 'ipplanner-fdba7',
    storageBucket: 'ipplanner-fdba7.appspot.com',
    iosBundleId: 'com.example.ipPlannerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGsK4rGgupqZCu1pwvMIUQglA_-yxnL8k',
    appId: '1:894560350962:ios:809ceb7501cfccee8b166b',
    messagingSenderId: '894560350962',
    projectId: 'ipplanner-fdba7',
    storageBucket: 'ipplanner-fdba7.appspot.com',
    iosBundleId: 'com.example.ipPlannerFlutter.RunnerTests',
  );
}
